# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build and export .ipa file"
  lane :build_ipa do
    # Build the app
    build_ios_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      export_method: "ad-hoc",
      export_options: {
        method: "ad-hoc",
        uploadBitcode: false,
        uploadSymbols: true,
        compileBitcode: false
      },
      output_directory: "build/ios",
      output_name: "ECommerce.ipa"
    )
  end

  desc "Build for App Store"
  lane :build_app_store do
    build_ios_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      export_method: "app-store",
      export_options: {
        method: "app-store",
        uploadBitcode: false,
        uploadSymbols: true,
        compileBitcode: false
      },
      output_directory: "build/ios",
      output_name: "ECommerce.ipa"
    )
  end

  desc "Build for Enterprise"
  lane :build_enterprise do
    build_ios_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      export_method: "enterprise",
      export_options: {
        method: "enterprise",
        uploadBitcode: false,
        uploadSymbols: true,
        compileBitcode: false
      },
      output_directory: "build/ios",
      output_name: "ECommerce.ipa"
    )
  end
end
