name: iOS Basic Build

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.5'
        channel: 'stable'
        
    - name: Install dependencies
      run: flutter pub get
      
    - name: Setup Xcode
      run: |
        sudo xcode-select --switch /Applications/Xcode.app
        sudo xcodebuild -license accept
        
    - name: Build iOS App
      run: |
        flutter build ios --release --no-codesign
        echo "iOS build completed"
        
    - name: List build files
      run: |
        find . -name "*.app" -type d
        find . -name "*.ipa" -type f
        ls -la ios/build/
        
    - name: Upload build directory
      uses: actions/upload-artifact@v4
      with:
        name: ios-build-files
        path: ios/build/
        retention-days: 30
        
    - name: Upload Flutter build
      uses: actions/upload-artifact@v4
      with:
        name: flutter-build
        path: build/
        retention-days: 30
