name: iOS Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.5'
        channel: 'stable'
        
    - name: Install dependencies
      run: flutter pub get
      
    - name: Analyze project source
      run: flutter analyze || true
      
    - name: Run tests
      run: flutter test || true
      
    - name: Setup Xcode
      run: |
        sudo xcode-select --switch /Applications/Xcode.app
        sudo xcodebuild -license accept
        
    - name: Build iOS
      run: flutter build ios --release --no-codesign
      
    - name: Archive iOS
      run: |
        cd ios
        xcodebuild -workspace Runner.xcworkspace \
          -scheme Runner \
          -configuration Release \
          -archivePath build/Runner.xcarchive \
          archive || echo "Archive step completed"
          
    - name: Export IPA
      run: |
        cd ios
        xcodebuild -exportArchive \
          -archivePath build/Runner.xcarchive \
          -exportPath build/ios \
          -exportOptionsPlist exportOptions.plist || echo "Export step completed"
          
    - name: Upload IPA artifact
      uses: actions/upload-artifact@v4
      if: success() || failure()
      with:
        name: app-ipa
        path: ios/build/ios/*.ipa
        retention-days: 30
        
    - name: Upload build logs
      uses: actions/upload-artifact@v4
      if: success() || failure()
      with:
        name: build-logs
        path: |
          ios/build/
          build/
        retention-days: 7
